# Generated by Django 5.1.7 on 2025-03-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=25)),
                ("product_description", models.CharField(max_length=100)),
                ("product_price", models.CharField(max_length=10)),
            ],
        ),
    ]
