# Generated by Django 5.1.7 on 2025-03-19 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productmodel",
            old_name="product_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="productmodel",
            old_name="product_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="productmodel",
            old_name="product_price",
            new_name="price",
        ),
    ]
